package com.example.boruto_compose.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF861fdb)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFf1daff)
val md_theme_light_onPrimaryContainer = Color(0xFF2c0052)
val md_theme_light_secondary = Color(0xFF744b9d)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFf1daff)
val md_theme_light_onSecondaryContainer = Color(0xFF2b0052)
val md_theme_light_tertiary = Color(0xFFbc1800)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdad1)
val md_theme_light_onTertiaryContainer = Color(0xFF3f0300)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFfbfdfd)
val md_theme_light_onBackground = Color(0xFF191c1d)
val md_theme_light_surface = Color(0xFFfbfdfd)
val md_theme_light_onSurface = Color(0xFF191c1d)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f1)
val md_theme_light_inverseSurface = Color(0xFF2d3132)
val md_theme_light_inversePrimary = Color(0xFFdfb7ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFdfb7ff)
val md_theme_dark_onPrimary = Color(0xFF490082)
val md_theme_dark_primaryContainer = Color(0xFF6800b5)
val md_theme_dark_onPrimaryContainer = Color(0xFFf1daff)
val md_theme_dark_secondary = Color(0xFFdeb7ff)
val md_theme_dark_onSecondary = Color(0xFF43196b)
val md_theme_dark_secondaryContainer = Color(0xFF5b3383)
val md_theme_dark_onSecondaryContainer = Color(0xFFf1daff)
val md_theme_dark_tertiary = Color(0xFFffb4a3)
val md_theme_dark_onTertiary = Color(0xFF660700)
val md_theme_dark_tertiaryContainer = Color(0xFF8f0f00)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdad1)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF191c1d)
val md_theme_dark_onBackground = Color(0xFFe0e3e3)
val md_theme_dark_surface = Color(0xFF191c1d)
val md_theme_dark_onSurface = Color(0xFFe0e3e3)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1d)
val md_theme_dark_inverseSurface = Color(0xFFe0e3e3)
val md_theme_dark_inversePrimary = Color(0xFF861fdb)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFF6750A4)
val error = Color(0xFFB3261E)